backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  accept_roles:
    - Admin

site_url: https://louiswhite.me
display_url: https://louiswhite.me
media_folder: public/media
publish_mode: editorial_workflow
show_preview_links: true
public_folder: public/
collections:
  - name: 'posts'
    label: 'Posts'
    folder: '/posts'
    preview_path: 'posts/{{slug}}'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
          date_format: 'YYYY-MM-DD',
          time_format: 'hh:mm:ss',
        }
      - {
          label: 'Last updated',
          name: 'lastUpdated',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
          date_format: 'YYYY-MM-DD',
          time_format: 'hh:mm:ss',
          default: '',
          required: false,
        }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Content', name: 'body', widget: 'markdown', required: true }
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home Page Content'
        name: 'home'
        file: 'content/home.md'
        fields:
          - {
              label: 'Page title',
              name: 'title',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Bio content',
              name: 'bio',
              widget: 'markdown',
              required: true,
              sanitize_preview: true,
            }
