backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  accept_roles:
    - Admin

site_url: https://louiswhite.me
display_url: https://louiswhite.me
media_folder: public/media
show_preview_links: true
public_folder: public/
collections:
  - name: 'posts'
    label: 'Posts'
    folder: '/posts'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          required: true,
        }
      - {
          label: 'Last updated',
          name: 'lastUpdated',
          widget: 'datetime',
          default: '',
        }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Content',
          name: 'content',
          widget: 'markdown',
          required: true,
        }
