name: CI pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 20
  PACKAGE_MANAGER: 'pnpm'


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          # version: 10
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          # cache: ${{ env.PACKAGE_MANAGER }}
      - name: Install dependecies
        run: npm install
      - run: npm run lint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          # version: 10
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          # cache: ${{ env.PACKAGE_MANAGER }}
      - name: Install dependencies
        run: npm install
      - run: npm run format:check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          # version: 10
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          # cache: ${{ env.PACKAGE_MANAGER }}
      - name: Install dependencies
        run: npm install
      - run: npm run test

  build:
    runs-on: ubuntu-latest
    env:
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          # version: 10
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.PACKAGE_MANAGER }}
      - name: Install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: Run lighthouse ci
        run: |
         npm install -g @lhci/cli@0.13.x
         lhci autorun --upload.token=${{ secrets.LHCI_BUILD_TOKEN }} --upload.serverBaseUrl=${{ secrets.LHCI_SERVER_BASE_URL}}


  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.PACKAGE_MANAGER }}
      - name: Install dependecies
        run: npm install
      - name: Publish to Chromatic
        uses: chromaui/action@v11
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: 'main'
          onlyChanged: true
          buildScriptName: 'storybook:build'
