name: Lighthouse
on:
  push:
    branches: 
      - main
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://www.louiswhite.me/
            https://www.louiswhite.me/blog
            https://www.louiswhite.me/contact
          # TODO: add back when you have config setup
          # configPath: './lighthouserc.json'