# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependecies
        run: npm install
      - name: Build
        run: npm run build
      - run: ls -la
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: '.next'
          production-branch: main
          production-deploy: ${{github.ref_name == 'main'}}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ github.event.head_commit.message }}
          github-deployment-environment: ${{ github.ref_name == 'main' && 'production' || 'preview'}}
          github-deployment-description: ${{ github.ref_name == 'main' && 'production deployment' || 'deploy preview'}}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
